name: Pull Request Title Validation

on:
  workflow_call:

jobs:

  Validate:

    name: Mandate Conventional Commit Standards
    runs-on: ubuntu-latest

    steps:

    - name: Test PR Title
      uses: aslafy-z/conventional-pr-title-action@v2.2.5
      with:
        preset: conventional-changelog-angular@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
